FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        cmake \
        git \
        clang \
        clang-format \
        clang-tidy \
        python3 \ 
        libbz2-dev \ 
        libz-dev \
        libicu-dev \
        libboost-all-dev 


WORKDIR /app

COPY . .

RUN cmake -S . -B build
RUN cmake --build build

RUN ctest --test-dir /app/build -C Debug -T test --output-on-failure -R Core.*
RUN ctest --test-dir /app/build -C Debug -T test --output-on-failure -R Indicators.*
RUN ctest --test-dir /app/build -C Debug -T test --output-on-failure -R MarketData.*

CMD ["/app/build/App/TradingEngine"]
