#stage 1
FROM ubuntu:24.04 AS builder

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        cmake \
        git \
        clang \
        clang-format \
        clang-tidy \
        python3 \ 
        libbz2-dev \ 
        libz-dev \
        libicu-dev \
        libboost-all-dev \
        ninja-build


WORKDIR /app

COPY . .

RUN cmake --preset debug 
RUN cmake --build --preset debug 
RUN cmake --preset release 
RUN cmake --build --preset release 

# stage 2
FROM ubuntu:24.04 AS runtime

WORKDIR /app

COPY --from=builder /app/build/release/App/TradingEngine /app/

CMD ["/app/TradingEngine"]
