project(CSVParser VERSION 1.0.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_library(CSVParser STATIC src/csv.cpp)
target_include_directories(CSVParser PUBLIC inc)
add_library(TradingEngine::Core::CSVParser ALIAS CSVParser)
add_subdirectory(test)
