name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --target builder -t trading_engine_builder -f docker/dockerfile .

      - name: Run debug tests
        run: |
              docker run --rm trading_engine_builder \
                ctest --test-dir /app/build/debug --output-on-failure

      - name: Run release tests
        run: |
              docker run --rm trading_engine_builder \
                ctest --test-dir /app/build/release --output-on-failure
      
      - name: Build runtime image
        run: docker build -t trading_engine -f docker/dockerfile .

      - name: Create container
        run: docker create --name trading_engine_tmp trading_engine

      - name: Extract binary
        run: docker cp trading_engine_tmp:/app/TradingEngine ./TradingEngine

      - name: Remove container
        run: docker rm trading_engine_tmp
      
      - name: Upload Trading Engine
        uses: actions/upload-artifact@v4
        with:
          name: trading-engine
          path: TradingEngine
      
      - name: Log in to GHCR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Tag Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker tag trading_engine ghcr.io/${{ github.repository }}:latest
      
      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push ghcr.io/${{ github.repository }}:latest

#       matrix:
#         build_type: [Debug, Release]
#         compiler: [gcc, clang]

#     env:
#       BUILD_DIR: ${{ github.workspace }}/build


#       - name: Install dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y \
#             libboost-all-dev \
#             clang \
#             clang-format

#       - name: Configure
#         run: >
#           cmake -S . -B "$BUILD_DIR"
#           -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
#           -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

#       - name: Build
#         run: cmake --build "$BUILD_DIR" --parallel

#       - name: Run tests
#         run: ctest --test-dir "$BUILD_DIR" --output-on-failure

#       - name: Check clang-format
#         run: cmake --build "$BUILD_DIR" --target check_format
